language: rust

rust:
  - stable

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

sudo: required

cache:
  apt: true
  directories:
    - $HOME/.cargo/bin
    - kcov/usr/local/bin
    - target/debug/deps

before_cache:
  - rm -rf /home/travis/.cargo/registry

branches:
  only:
    - staging
    - trying
    - master

matrix:
  allow_failures:
    - rust: nightly

  include:
  - rust: nightly

    addons:
      apt:
        packages:
          - binutils-dev
          - libcurl4-openssl-dev
          - zlib1g-dev
          - libdw-dev
          - libiberty-dev

    before_script:
    - rustup component add clippy
    - rustup component add rustfmt

    script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
    - cargo test

    after_success:
    - ./.travis/coverage.sh
